-- CREATE TABLE IF NOT EXISTS tableA(id serial PRIMARY KEY, name VARCHAR(100));
-- CREATE TABLE IF NOT EXISTS tableC(id serial PRIMARY KEY, name VARCHAR(100));

CREATE TABLE tableB (
id serial PRIMARY KEY, name VARCHAR(100), idA int, idC int,
FOREIGN KEY (idA) REFERENCES tableA (id) ON DELETE CASCADE ON UPDATE RESTRICT,
FOREIGN KEY (idC) REFERENCES tableC (id) ON DELETE RESTRICT ON UPDATE CASCADE
);

