CREATE DATABASE LR1;

CREATE TABLE films(
	code 		char(5) CONSTRAINT firstke PRIMARY KEY,
	title 		varchar(40) NOT NULL,
	did 		integer NOT NULL,
	date_prod 	date,
	kind		varchar(10),
	len 		interval hour to minute
);

CREATE local temp TABLE distributors(did integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, name varchar(40) NOT NULL CHECK (name <> ''));

ALTER TABLE films ADD id int null;

ALTER TABLE films DROP id;

ALTER TABLE distributors ALTER COLUMN address TYPE varchar(80), ALTER COLUMN name TYPE varchar(100);

INSERT into sales (item, quantity) values ('book',3);
SELECT * from sales;

UPDATE sales set quantity = quantity + 1 where item = 'book';
SELECT item from sales;

DELETE from sales where item = 'book';
SELECT * from sales;

CREATE TABLE top_rated_films();
CREATE TABLE most_popular_films();

-- 1. Объединение
SELECT * FROM top_rated_films
UNION ALL
SELECT * FROM most_popular_films
ORDER BY title;

-- 2. Пересечение
SELECT top_rated_films
FROM A
INTERSECT
SELECT most_popular_films
FROM B;

-- 3. Вычитание
SELECT * FROM top_rated_films
EXCEPT
SELECT * FROM most_popular_films;

-- 4. Декартово произведение
SELECT * FROM T1 CROSS JOIN T2;
SELECT * FROM T1, T2;
SELECT * FROM T1 INNER JOIN T2 ON TRUE;

-- 5. Выборка
SELECT * FROM films f WHERE f.rating > 5 and f.critics > 5;

-- 6. Проекция
SELECT films.name, films.e_rating FROM films f;

-- 7. Деление
SELECT * FROM films
WHERE genre @> ARRAY['БОЕВИК', 'КОМЕДИЯ'];